### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [sowoi/nextcloud-talk-bot#1]
https://hosted.weblate.org/projects/nextcloudtalkbot/user-intraction/#information
says LGPLv3
whereas
https://github.com/sowoi/nextcloud-talk-bot/blob/main/LICENSE
says GPLv3

It can be changed in
https://hosted.weblate.org/settings/nextcloudtalkbot/user-intraction/
and
https://hosted.weblate.org/settings/nextcloudtalkbot/glossary/

If you add "kingu" in https://hosted.weblate.org/access/nextcloudtalkbot/#users
I can look for more things to fix and report back.

**Comment by sowoi** [comment]
Thanks for the tip. I have changed that.
