### ISSUE TITLE
Weblate integration

### ISSUE THREAD

**Issue by comradekingu** [sowoi/nextcloud-talk-bot#45]
https://docs.weblate.org/en/latest/admin/continuous.html#github-setup is missing
and possibly the  https://github.com/weblate user could be added to the org.

**Comment by sowoi** [comment]
Thank you for your efforts. The Continoous localization feature was the reason why I decided to use weblate instead of  transifex or something else. I haven't gotten around to writing a workflow for it yet.

**Comment by sowoi** [comment]
Fixed

**Comment by comradekingu** [comment]
@sowoi 
Got a message from the WL top-level admin.
If you can set up https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github I think it should work. I'll request approval for libre hosting so the project doesn't get deleted.
